### ISSUE TITLE
✨ TODO

### ISSUE THREAD

**Issue by sengjun0624** [LeeJaeJun1/Baekjoon#2]
- [ ] 알고리즘 자료구조 학습하기
- https://inpa.tistory.com/category/%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0
- https://www.acmicpc.net/workbook/view/415
- 배열 , 트리 , 스택, 큐 ,우선순위큐 ,덱 , 맵 ,그래프
- [ ] 1일 1 백준 및 커밋
- [ ] 문제 풀이에 대해 왜 그렇게 했고 어떻게 풀었는지 고민하기
- [ ] 기술스택 고민하기 (웹, 안드로이드 ,iOS , AI , 백엔드)
